# macOS part of alacritty.toml, imported from there.

[font]
size = 16.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u0002"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002("
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0002)"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00020"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00020"
key = "`"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Shift|Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002r"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002u"
key = "U"
mods = "Command"

[[keyboard.bindings]]
command = { program = "/bin/sh", args = ["-c", "$HOME/.scripts/alacritty_font_size.sh"] }
key = "Semicolon"
mods = "Command"

[terminal.shell]
program = "/bin/zsh"
